version: "3.9"
services:
  my-app:
    container_name: my_app
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/usr/src/.env
    command: gunicorn server:app --bind 0.0.0.0:8000